volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_django_media: {}
  production_django_staticfiles: {}
  
  production_redis_data: {}
  
networks:
  backend:

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: backend_production_django
    volumes:
      - production_django_media:/app/backend/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    networks:
      - backend
    restart: always

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: backend_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    networks:
      - backend
    restart: always

  redis:
    image: docker.io/redis:6
    
    volumes:
      - production_redis_data:/data
    
    networks:
      - backend
    restart: always

  celeryworker:
    <<: *django
    image: backend_production_celeryworker
    command: /start-celeryworker
    networks:
      - backend
    restart: always

  celerybeat:
    <<: *django
    image: backend_production_celerybeat
    command: /start-celerybeat
    networks:
      - backend
    restart: always

  flower:
    <<: *django
    image: backend_production_flower
    command: /start-flower
    networks:
      - backend
    restart: always

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: backend_production_nginx
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
    ports:
      - 127.0.0.1:8080:80
    networks:
      - backend
    restart: always
